name: bot
on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Run docker action
    - name: Hello world action step
      id: hello
      uses: benoitf/che-triage@0.0.1
      with:
        write-token: ${{ secrets.GITHUB_TOKEN }}
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
      
